defaults:
  - model: lcnn
  - writer: wandb
  - metrics: eer
  - datasets: asvspoof
  - dataloader: example  # Uses automatic shuffle logic: train=True, dev/test=False.
  - transforms: fft_final
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
  betas: [0.9, 0.999]
  eps: 1e-8

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 20

loss_function:
  _target_: src.loss.StandardCrossEntropyLoss

trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: null
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: auto
  override: False
  monitor: "min eval_EER"
  save_period: 5
  early_stop: 20
  save_dir: "saved"
  seed: 0

writer:
  run_name: "asvspoof_lcnn"
  project_name: "voice-antispoofing"
  tags: ["lcnn", "voice-antispoofing", "fft"] 